Board = {
  clientId: "chessboard-js-board",
  initialBoard: {
    pieces: {a8:"bR", b8:"bN", c8:"bB", d8:"bQ", e8:"bK", f8:"bB", g8:"bN", h8:"bR",
             a7:"bP", b7:"bP", c7:"bP", d7:"bP", e7:"bP", f7:"bP", g7:"bP", h7:"bP",
             a2:"wP", b2:"wP", c2:"wP", d2:"wP", e2:"wP", f2:"wP", g2:"wP", h2:"wP",
             a1:"wR", b1:"wN", c1:"wB", d1:"wQ", e1:"wK", f1:"wB", g1:"wN", h1:"wR"}
  },
  render: function(board) {
    console.info("Rendering board");
    if ($("#" + this.clientId).length) {
      return new ChessBoard(this.clientId, {
        draggable: true,
        onDrop: function(source, target) {
          MovesCollection.insert({
            from: source,
            to: target,
            board: Board.move(board, source, target)
          });
        },
        position: board.pieces
      });
    }
  },
  move: function(board, from, to) {
    var mover, newPieces;
    newPieces = _.clone(board.pieces);
    mover = newPieces[from];
    delete newPieces[from];
    newPieces[to] = mover;
    return {
      lastMove: {
        from: from,
        to: to
      },
      pieces: newPieces
    };
  }
};

// ---
// generated by coffee-script 1.9.2
